version: '3.8'
services:
  api:
    build: '.'
    image: 'node_app:latest'
    container_name: 'node_api'
    ports:
      - 5000:5000
    depends_on: 
      - 'db'
  db:
    container_name: 'mongodb'
    image: 'mongo:latest'
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=testUser
      - MONGO_INITDB_ROOT_PASSWORD=testPassword
      - MONGO_INITDB_DATABASE=books
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro